eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9080/eureka/    # http://arch-cloud:8080/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.demo-microservice}
spring:
  application:
    name: demo-microservice
server:
  port: 9083
